package com.yuzhi.dtadmin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApprovalItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalItemAllPropertiesEquals(ApprovalItem expected, ApprovalItem actual) {
        assertApprovalItemAutoGeneratedPropertiesEquals(expected, actual);
        assertApprovalItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalItemAllUpdatablePropertiesEquals(ApprovalItem expected, ApprovalItem actual) {
        assertApprovalItemUpdatableFieldsEquals(expected, actual);
        assertApprovalItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalItemAutoGeneratedPropertiesEquals(ApprovalItem expected, ApprovalItem actual) {
        assertThat(actual)
            .as("Verify ApprovalItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalItemUpdatableFieldsEquals(ApprovalItem expected, ApprovalItem actual) {
        assertThat(actual)
            .as("Verify ApprovalItem relevant properties")
            .satisfies(a -> assertThat(a.getTargetKind()).as("check targetKind").isEqualTo(expected.getTargetKind()))
            .satisfies(a -> assertThat(a.getTargetId()).as("check targetId").isEqualTo(expected.getTargetId()))
            .satisfies(a -> assertThat(a.getSeqNumber()).as("check seqNumber").isEqualTo(expected.getSeqNumber()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalItemUpdatableRelationshipsEquals(ApprovalItem expected, ApprovalItem actual) {
        assertThat(actual)
            .as("Verify ApprovalItem relationships")
            .satisfies(a -> assertThat(a.getRequest()).as("check request").isEqualTo(expected.getRequest()));
    }
}
