package com.yuzhi.dtadmin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExternalResourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalResourceAllPropertiesEquals(ExternalResource expected, ExternalResource actual) {
        assertExternalResourceAutoGeneratedPropertiesEquals(expected, actual);
        assertExternalResourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalResourceAllUpdatablePropertiesEquals(ExternalResource expected, ExternalResource actual) {
        assertExternalResourceUpdatableFieldsEquals(expected, actual);
        assertExternalResourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalResourceAutoGeneratedPropertiesEquals(ExternalResource expected, ExternalResource actual) {
        assertThat(actual)
            .as("Verify ExternalResource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalResourceUpdatableFieldsEquals(ExternalResource expected, ExternalResource actual) {
        assertThat(actual)
            .as("Verify ExternalResource relevant properties")
            .satisfies(a -> assertThat(a.getUrn()).as("check urn").isEqualTo(expected.getUrn()))
            .satisfies(a -> assertThat(a.getMaxLevel()).as("check maxLevel").isEqualTo(expected.getMaxLevel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalResourceUpdatableRelationshipsEquals(ExternalResource expected, ExternalResource actual) {
        // empty method
    }
}
